spring.application.name=shecode

spring.datasource.url=jdbc:postgresql://localhost:5432/shecode
spring.datasource.username=shecode
spring.datasource.password=shecode

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true